#!/usr/bin/env bash

cd "$(dirname "$0")"

export HSA_OVERRIDE_GFX_VERSION=10.3.0

PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512 python launch.py --precision full --no-half --opt-sub-quad-attention $@
