#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

export HSA_OVERRIDE_GFX_VERSION="10.3.0"

if [[ "$CONDA_DEFAULT_ENV" != "ldm" ]]; then
  echo "Activiating conda environment"
  source ~/.miniconda3/etc/profile.d/conda.sh
  conda activate ldm
fi

echo "Applying gradio fix"
mkdir /tmp/gradio/

PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512 python launch.py --precision full --no-half --opt-sub-quad-attention $@
